githubUser: {
  login: 'llere-alt',
  id: 63543622,
  node_id: 'MDQ6VXNlcjYzNTQzNjIy',
  avatar_url: 'https://avatars3.githubusercontent.com/u/63543622?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/llere-alt',
  html_url: 'https://github.com/llere-alt',
  followers_url: 'https://api.github.com/users/llere-alt/followers',
  following_url: 'https://api.github.com/users/llere-alt/following{/other_user}',
  gists_url: 'https://api.github.com/users/llere-alt/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/llere-alt/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/llere-alt/subscriptions',
  organizations_url: 'https://api.github.com/users/llere-alt/orgs',
  repos_url: 'https://api.github.com/users/llere-alt/repos',
  events_url: 'https://api.github.com/users/llere-alt/events{/privacy}',
  received_events_url: 'https://api.github.com/users/llere-alt/received_events',
  type: 'User',
  site_admin: false,
  name: 'Daniel Alejandro Hernández Llerena',
  company: null,
  blog: 'https://www.linkedin.com/in/daniel-hernandez-ller/',
  location: 'Barcelona, Spain',
  email: 'dhdezllerena94@gmail.com',
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 12,
  public_gists: 0,
  followers: 2,
  following: 6,
  created_at: '2020-04-12T11:54:22Z',
  updated_at: '2020-10-10T18:35:23Z',
  private_gists: 1,
  total_private_repos: 49,
  owned_private_repos: 2,
  disk_usage: 1574,
  collaborators: 1,
  two_factor_authentication: false,
  plan: {
    name: 'pro',
    space: 976562499,
    collaborators: 0,
    private_repos: 9999
  }
}