// type Mutation {
//   authorizeWithGithub(code: String!): AuthPayload!
//   CreateEvent(input: EventInput!): EventData!
//   CreateUserData(input: UserInput!, id: Int): User!
// }

// type User {
//   id: Int
//   email: String
//   name: String
//   githubLogin: String
//   githubToken: String
//   location: String
//   avatar: String
//   linkedIn: String
//   gitHub:String
//   portfolio: String
//   bio: String
//   userStacks: [userStacks]
// }

// type userStacks {
//   userStacks: String
// }

// input UserInput {
//   linkedIn: String
//   gitHub: String
//   portfolio: String
//   bio: String
//   userStacks: [userStacks]
// }