export const stacksOptions = [
  { value: 'JavaScript', label: 'JavaScript' },
  { value: 'Python', label: 'Python' },
  { value: 'Rust', label: 'Rust' },
  { value: 'Java', label: 'Java' },
  { value: 'C', label: 'C' },
  { value: 'C++', label: 'C++' },
  { value: 'C#', label: 'C#' },
  { value: 'Golang', label: 'Golang' },
  { value: 'R', label: 'R' },
  { value: 'React', label: 'React' },
  { value: 'R', label: 'R' },
  { value: 'PHP', label: 'PHP' },
  { value: 'Swift', label: 'Swift' },
  { value: 'TypeScript', label: 'TypeScript' },
  { value: 'React Native', label: 'React Native' },
  { value: 'Angular', label: 'Angular' },
  { value: 'Ruby', label: 'Ruby' },
  { value: 'NextJs', label: 'NextJs' },
  { value: 'GraphQl', label: 'GraphQl' },
  { value: 'React Query', label: 'React Query' },
  { value: 'Apollo Client', label: 'Apollo Client' },
  { value: 'Apollo Server', label: 'Apollo Server' },
  { value: 'Redux', label: 'Redux' },
  { value: 'NestJs', label: 'NestJs' },
  { value: 'Rest', label: 'Rest' },
  { value: 'Express', label: 'Express' },
  { value: 'Jest', label: 'Jest' },
  { value: 'Mongodb', label: 'Mongodb' },
  { value: 'Sequelize', label: 'Sequelize' },
  { value: 'Postgres', label: 'Postgres' },
  { value: 'HTML', label: 'HTML' },
  { value: 'CSS', label: 'CSS' },
  { value: 'SCSS', label: 'SCSS' },
  { value: 'Formik', label: 'Formik' },
  { value: 'oAuth', label: 'oAuth' },
];
