export const stacksOptions = [
  { value: 'JavaScript', label: 'JavaScript' },
  { value: 'Python', label: 'Python' },
  { value: 'Rust', label: 'Rust' },
  { value: 'Java', label: 'Java' },
  { value: 'C', label: 'C' },
  { value: 'C++', label: 'C++' },
  { value: 'C#', label: 'C#' },
  { value: 'Golang', label: 'Golang' },
  { value: 'R', label: 'R' },
  { value: 'React', label: 'React' },
  { value: 'R', label: 'R' },
  { value: 'PHP', label: 'PHP' },
  { value: 'Swift', label: 'Swift' },
  { value: 'TypeScript', label: 'TypeScript' },
  { value: 'React Native', label: 'React Native' },
  { value: 'Angular', label: 'Angular' },
  { value: 'Ruby', label: 'Ruby' },
];
